services:

  frontend:
    container_name: frontend
    image: lucianobc/front_sanos_salvos:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:80"
    restart: unless-stopped
    networks:
      - sanos-salvos

networks:
  sanos-salvos:
    external: true
    name: mascotas_sanos-y-salvos-net
