services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - sanos-salvos

networks:
  sanos-salvos:
    external: true
    name: mascotas_sanos-y-salvos-net
